# Generated by Django 3.0.5 on 2020-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(max_length=100)),
                ('product_quantity', models.IntegerField(default=1, max_length=10)),
            ],
        ),
    ]
