# Generated by Django 3.0.5 on 2020-05-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_userprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductmodel',
            name='product_name',
            field=models.CharField(choices=[('EARPHONE', 'earphone'), ('HEADPHONE', 'headphone'), ('LAPTOP', 'laptop')], max_length=20),
        ),
    ]
