# Generated by Django 3.0.5 on 2020-05-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200524_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=50)),
                ('order_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_status', models.CharField(max_length=10)),
            ],
        ),
    ]
