# Generated by Django 3.0.5 on 2020-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_placeordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeordermodel',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='placeordermodel',
            name='product_quantity',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1),
        ),
    ]
