# Generated by Django 3.0.5 on 2020-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200524_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='order_by',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_price',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_status',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
