# Generated by Django 3.0.5 on 2020-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200524_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_quantity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
