# Generated by Django 3.0.5 on 2020-05-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200524_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_price',
            field=models.IntegerField(blank=True),
        ),
    ]
