# Generated by Django 3.0.5 on 2020-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200524_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
