# Generated by Django 3.0.5 on 2020-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200524_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeordermodel',
            name='order_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placeordermodel',
            name='product_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
