# Generated by Django 3.0.5 on 2020-05-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200524_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceOrderModel',
        ),
    ]
