# Generated by Django 3.0.5 on 2020-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_placeordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrderModel',
            fields=[
                ('order_by', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_quantity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('product_price', models.IntegerField(null=True)),
                ('product_status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
