# Generated by Django 3.0.5 on 2020-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_placeordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceOrderModel',
        ),
    ]
