# Generated by Django 3.0.5 on 2020-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_placeordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=20, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_quantity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('product_price', models.IntegerField(null=True)),
                ('product_status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
